spring.datasource.url=jdbc:mysql://localhost:3306/municity?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# --- CONTROL DE BASE DE DATOS ---
# DESCOMENTA la siguiente linea para hacer un "FRESH" (Borra todo y recrea las tablas limpias)
spring.jpa.hibernate.ddl-auto=create

# Mantener activo para el dia a dia (Solo actualiza los cambios sin borrar datos)
#spring.jpa.hibernate.ddl-auto=update
# --------------------------------

spring.jpa.show-sql=true
# opcional
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB

app.upload.base-dir=uploads

app.jwt.secret=municity-super-secret-key-2026-municipio-seguro
app.jwt.expiration-ms=86400000
