spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/municity?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

# --- CONTROL DE BASE DE DATOS ---
# DESCOMENTA la siguiente linea para hacer un "FRESH" (Borra todo y recrea las tablas limpias)
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

# Mantener activo para el dia a dia (Solo actualiza los cambios sin borrar datos)
#spring.jpa.hibernate.ddl-auto=update
# --------------------------------

spring.jpa.show-sql=true
# opcional
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB

app.upload.base-dir=${APP_UPLOAD_BASE_DIR:uploads}

app.jwt.secret=${APP_JWT_SECRET:municity-super-secret-key-2026-municipio-seguro}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS:86400000}
